### PR TITLE
Rebase 080322

### PR DESCRIPTION
**Pull request by darincomeau**
Rebases cime submodule to current hash (`a00a6ed `) used in E3SM master

### CODE REVIEW

**Comment by darincomeau** [comment]
I thought the issue with https://github.com/darincomeau/E3SM/pull/16 was that I needed to separately rebase the cime submodule first, but it's still showing a conflict.

I think the correct approach is to merge the rebase branch into the `E3SMv2-Arctic` branch locally, and then push that branch, but it makes me nervous to push directly without having a PR.

**Comment by darincomeau** [comment]
@apcraig @milenaveneziani I think I've *finally* got this sorted. The extra step needed was to merge the `E3SMv2-Arctic` branch into this `rebase-080322` branch, and the conflict goes away.

For the record, here's what I did:
```
git clone git@github.com:darincomeau/cime.git
cd cime
git checkout -b rebase-080322
git remote add cime git@github.com:ESMCI/cime.git
git fetch --all
git rebase a00a6ed # current cime hash e3sm points to
# emacs CIME/case/case.py # resolve conflict
git add CIME/case/case.py
git rebase --continue
# now merge E3SMv2-Arctic into this branch
git pull origin E3SMv2-Arctic
git checkout rebase-080322 # probably unnecessary, already there
git merge origin/E3SMv2-Arctic
git push -u origin rebase-080322
```

I think this is now safe to merge, and then I can move up to update the cime hash in `E3SMv2-Arctic`, then do that rebase.

**Comment by darincomeau** [comment]
I realize with all the changes it's nearly impossible to see here, but here are the lines in `CIME/case/case.py`, L2001, in this branch that were the source of the conflict (confirming DoD machine support is here):
```
        # special case for aprun
        if executable is not None and "aprun" in executable and not "theta" in self.get_value("MACH") and not "onyx" in self.get_value("MACH") and not "warhawk" in self.get_value("MACH") and not "blackbird" in self.get_va\
lue("MACH"):
            aprun_args, num_nodes = get_aprun_cmd_for_case(self, run_exe, overrides=overrides)[0:2]
            if job in ("case.run","case.test"):
                expect( (num_nodes + self.spare_nodes) == self.num_nodes, "Not using optimized num nodes")
            return self.get_resolved_value(executable + aprun_args + " " + run_misc_suffix, allow_unresolved_envvars=allow_unresolved_envvars)
```

**Review by apcraig — APPROVED** [review]
Thanks Darin, looks like you verified the DOD stuff is still there, so that's fine for me.  I'll test once E3SM has all the updates.

**Review by milenaveneziani — APPROVED** [review]
I'm glad you were able to sort this out, Darin.

**Pull request merged**
